#!/bin/sh -e
#  This file is called when the domain name is changed, to change any
#  named configuration files affected.
#
#  The first argument is the old domain name,
#  the second argument is the new domain name

#  Copyright 2008, One Laptop per Child
#  Author: John Watlington <wad@laptop.org>
#  License: GPL v2

#  This is the name of the service (for stopping and restarting)
SERVICE_NAME=squid

#  This is a list of files related to this service which will have
#  the domain name globally replaced inside them
CONFIG_LIST="/etc/squid/squid.conf"

#  This is the suffix which original versions of modified files will have
BACKUP_SUFFIX=old

old_name=$1
new_name=$2

# echo Changing $SERVICE_NAME config from $old_name to $new_name

service $SERVICE_NAME stop

for config in $CONFIG_LIST;
do
  mv $config $config.$BACKUP_SUFFIX
  sed -e s/$old_name/$new_name/ $config.$BACKUP_SUFFIX > $config ;
done

service $SERVICE_NAME start

