install:

	install -D files/settings.py.in  $(DESTDIR)/etc/pathagar/settings.py.in
	install -D files/pathagar.conf.in  $(DESTDIR)/etc/pathagar/pathagar.conf.in
	install -D files/pathagar.wsgi  $(DESTDIR)/etc/pathagar/pathagar.wsgi
