#!/bin/bash
PLAYBOOK="xsce-base.yml"
INVENTORY="ansible_hosts"
SELINUX_BEFORE=""
SELINUX_AFTER=""
# if not the first run, repo location is here

if [ -f /etc/xsce/xsce.env ]
then
  . /etc/xsce/xsce.env
  cd $XSCE_DIR
fi

if [ ! -f $PLAYBOOK ]
then
 echo "XSCE Playbook not found."
 echo "Please run this command from the top level of the git repo."
 echo "Exiting."
 exit
fi

# copy var files to /etc/xsce for subsequent use
if [ ! -f /etc/xsce/config_vars.yml ]
then
  ./install-init
fi

if [ -f /etc/selinux/config ]
then
 SELINUX_BEFORE=`cat /etc/selinux/config | gawk -F= '/^SELINUX=/{ print $2 }'`
fi

export ANSIBLE_LOG_PATH="xsce-install.log"
ansible-playbook -i $INVENTORY $PLAYBOOK --connection=local

if [ -f /etc/selinux/config ]
then
 SELINUX_AFTER=`cat /etc/selinux/config | gawk -F= '/^SELINUX=/{ print $2 }'`
fi

if [ "$SELINUX_BEFORE" != "$SELINUX_AFTER" ]; then
  echo "You should reboot now."
fi
