#!/bin/bash

PLAYBOOK="xsce-base.yml"
INVENTORY="ansible_hosts"

SELINUX_BEFORE=`cat /etc/selinux/config | gawk -F= '/^SELINUX=/{ print $2 }'`

export ANSIBLE_LOG_PATH="xsce-install.log"
ansible-playbook -i $INVENTORY $PLAYBOOK --connection=local 

SELINUX_AFTER=`cat /etc/selinux/config | gawk -F= '/^SELINUX=/{ print $2 }'`

if [ "$SELINUX_BEFORE" != "$SELINUX_AFTER" ]; then
  echo "Rebooting ..."
  reboot
fi
