#!/bin/bash
MENU_VERSION="0"
NEW_VERSION="1"
PLAYBOOK="install-menu.yml"

if [ -f /etc/xsce/xsce.env ]
then
 . /etc/xsce/xsce.env
 NEW_VERSION=`cat $XSCE_DIR/roles/1-prep/defaults/main.yml | grep new_menu_version | awk -F ": " '{print $2}'`
fi

if [ -f /etc/xsce/config_vars.yml ] && [ "$MENU_VERSION" == "$NEW_VERSION" ]
then
 exit 0
fi

if [ ! -f $PLAYBOOK ]
then
 echo "XSCE Playbook not found."
 echo "Please run this command from the top level of the git repo."
 echo "Exiting."
 exit 1
fi

INVENTORY="ansible_hosts"

XSCE_DIR=`pwd`
export ANSIBLE_LOG_PATH="$XSCE_DIR/xsce-install.log"
ansible-playbook -i $INVENTORY $PLAYBOOK --connection=local
