#!/bin/bash
if [ -f xsce.yml ]
 then
 PLAYBOOK="xsce.yml"
 INVENTORY="ansible_hosts"
 echo "Running local playbooks! "
 else
 if [ -f /var/local/xsce/xsce.yml ]
 then
 PLAYBOOK="/var/local/xsce/xsce.yml"
 INVENTORY="/var/local/xsce/ansible_hosts"
 echo "Running rpm provided playbooks ! "
fi
fi
if [ "$PLAYBOOK" == "" ]
	then
	echo "rpm is not installed, and local playbook wasn't found!"
	exit
	fi

#Domain change
if [ x"$1" != x ]
then
  if echo $1 | grep -sq "\."
      then
      XSHOSTNAME=`echo $1 | cut -d\. -f1`
      XSDOMAIN=`echo $1 | cut -d\. -f2-`
      ARGS="--extra-vars \"xsce_hostname=$XSHOSTNAME xsce_domain=$XSDOMAIN\""
       echo $ARGS
    else
      XSHOSTNAME=$1
      ARGS="--extra-vars \"xsce_hostname=$XSHOSTNAME\""
     fi
fi

ansible-playbook -i $INVENTORY $PLAYBOOK "${ARGS}" --connection=local 
