#!/bin/bash
# script to run a specific tag in the current playbook
if [ $# -ne 1 ]; then
	echo "usage: $0 <tagname>"
	echo
	echo " If you would like a list of possible values, enter $0 XXX"
	exit 1
fi
ansible-playbook -i ansible_hosts xsce.yml --connection=local --tags="""$1"""

