#!/bin/bash
# replacement for monolithic function definitions
FUNCTIONSDIR=/usr/share/xs-config/sh.d
pushd $FUNCTIONSDIR
for script in `find $FUNCTIONSDIR -maxdepth 1 -type file`
        echo $script
        if [ ! -z $script ]; then
            source "$script"
        fi
done
popd
