#!/bin/bash 
# tools to create, manage, simplify services and modules on XS server
case "$1" in
"mktree")
	if [ $# -eq 2 -a $2 = "all" ]; then
		MODULES=`cat modules_manifest`
	fi
	if [ $# -eq 2 -a $2 != "all" ]; then
		MODULES=$2
	fi
	if [ $# -eq 1 ]; then
		MODULES=`cat modules_manifest`
	fi
	for mod in $MODULES; do
		mkdir -p plugins.d/$mod
		pushd plugins.d/$mod
		mkdir -p yum files
		touch sequence enabled $mod.sh Makefile manifest \
			README description
        chmod 755 $mod.sh
		popd
	done
	;;
"mklinks")
	if [ $# -eq 2 -a $2 = "all" ]; then
		MODULES=`cat modules_manifest`
	fi
	if [ $# -eq 2 -a $2 != "all" ]; then
		MODULES=$2
	fi
	if [ $# -eq 1 ]; then
		MODULES=`cat modules_manifest`
	fi
	for mod in $MODULES; do
		pushd plugins.d/$mod
		seq="50"
		if [ -f sequence ]; then
		        newseq=`cat sequence`
		fi
		if [ -nz $newseq ]; then
		        seq=$newseq
		fi
                ln -s ../../$mod ../active.d/$seq-$mod
                popd
	done
	;;
"yum")
        for mod in `ls plugins.d`; do
                echo `ls -1 plugins.d/$mod/yum/`
        done
        ;;
                
"functions")
        curdir=`pwd`
        for mod in `ls plugins.d`; do
                cd plugins.d/$mod
                echo `ls -1 *.sh`
                cd $curdir
        done
        ;;
                
"exec")
        curdir=`pwd`
        for mod in `ls plugins.d`; do
                cd plugins.d/$mod
                script=`ls -1 *.sh`
                if [ ! -z $script ]; then
                    source "./$script"
                fi
                cd $curdir
        done
        ;;
"savetree")
        mkdir -p ../plugins.d.backup
        cp -rp ./plugins.d/* ../plugins.d.backup
        ;;
"restoretree")
        mkdir -p ./modules.test
        cp -rp ../plugins.d.backup/* ./modules.test
        ;;
*)
	ls  plugins.d
	;;
esac
