#!/bin/bash
# tools to create, manage, simplify services and modules on XS server
case "$1" in
"mktree")
# Read plugin names from m_manifest (or 2nd parameter) and create plugin tree
	if [ $# -eq 2 -a $2 = "all" ]; then
		MODULES=`cat m_manifest`
	fi
	if [ $# -eq 2 -a $2 != "all" ]; then
		MODULES=$2
	fi
	if [ $# -eq 1 ]; then
		MODULES=`cat m_manifest`
	fi
	for mod in $MODULES; do
		mkdir -p plugins.d/$mod
		pushd plugins.d/$mod
		mkdir -p yum files
		touch $mod.sh Makefile $mod.manifest $mod.README 
        chmod 755 $mod.sh
		popd
	done
	;;
"mklinks")
# probably will delete this function
	if [ $# -eq 2 -a $2 = "all" ]; then
		MODULES=`cat m_manifest`
	fi
	if [ $# -eq 2 -a $2 != "all" ]; then
		MODULES=$2
	fi
	if [ $# -eq 1 ]; then
		MODULES=`cat m_manifest`
	fi
	for mod in $MODULES; do
		pushd plugins.d/$mod
		seq="50"
		if [ -f sequence ]; then
		        newseq=`cat sequence`
		fi
		if [ -nz $newseq ]; then
		        seq=$newseq
		fi
                ln -s ../../$mod ../active.d/$seq-$mod
                popd
	done
	;;
"yum")
# echo the yum modules in all the plugins
        for mod in `ls plugins.d`; do
                echo `ls -1 plugins.d/$mod/yum/`
        done
        ;;

"functions")
# echo the function names (*.sh) in the plugin tree
        curdir=`pwd`
        for mod in `ls plugins.d`; do
                cd plugins.d/$mod
                echo `ls -1 *.sh`
                cd $curdir
        done
        ;;

"exec")
# source all the functions in the plugin tree
        curdir=`pwd`
        for mod in `ls plugins.d`; do
                cd plugins.d/$mod
                script=`ls -1 *.sh`
                if [ ! -z $script ]; then
                    source "./$script"
                fi
                cd $curdir
        done
        ;;
"savetree")
# copy the plugin tree to ../plugins.d.backup, or 2nd parameter
        target=../plugins.d.backup
        if [ $# = 1 ]; then
            target=$1
        fi
        mkdir -p $target
        cp -rp ./plugins.d/* $target
        ;;
"restoretree")
# copy the plugin tree from ../plugins.d.backup, or 2nd parameter to ./plugins.test
        source=../plugins.d.backup
        if [ $# = 1 -a -d $1 ]; then
            source=$1
        fi
        mkdir -p ./plugins.test
        cp -rp $source/* ./modules.test
        ;;
"git2linux")
# extract the current git branch to a tree one directory up from current
        target=../linuxtree
        if [ $# = 1 ];then
            target=../$1
        fi
        export DESTDIR=$target
        mkdir -p $target
        make -e install
        ;;
"mkmake")
# use manifest to generate Makefiles in each plugin
    curdir=`pwd`
    MKDIR_MAKEFILE=$curdir/plugins.d/Makefile
    rm -f $MKDIR_MAKEFILE
    # scan through all the files in the input tree, and create the directories
    # use an array to eliminate duplicates
    for mod in `ls plugins.d`; do
        cd plugins.d/$mod
        #echo "$PWD/$mod.manifest"
        if [ -f ./$mod.manifest ]; then
            manlist+=" plugins.d/$mod/$mod.manifest"
        fi
        cd $curdir
    done
    echo "install:" >>$MKDIR_MAKEFILE
    cat $manlist | gawk -v mkfile=$MKDIR_MAKEFILE '{
        line = $0
        nibbles[0]=""
        for (i in nibbles) {delete nibble[i]}
        print $0
        directories[0]=""
        num = split($0,nibbles,"/")
        #for (i in nibbles) {print( nibbles[i])}
        path = ""
        for (i=1; i<num; i++){
            path = path nibbles[i] "/"
            # clip off the leading slash
            #sub(/^\//,"",path)
            #print path
            if (!( path in directories)) {
                makef = sprintf("\tinstall -D -d  \044(DESTDIR)%s",path)
                cmd = sprintf("echo '\''%s'\'' >> %s", makef, mkfile)
                #print(cmd "  " path)
                system(cmd)
                directories[path]=""
            }
        }
    }'
    for mod in `ls plugins.d`; do
        cd plugins.d/$mod
        rm -f Makefile
        echo "install:" >> Makefile
        #echo `cat $mod.manifest `
        if [ -f $mod.manifest ]; then
            cat $mod.manifest | gawk -v pluginloc=$mod '{
            ar[0] = ""
            num = split($0,ar,"/")
            path = ""
            for (i=1; i<num; i++){
                path = path ar[i] "/"
            }
            makef = sprintf("\tinstall -D files/%s \044(DESTDIR)%s",ar[num],path )
            cmd = sprintf("echo '\''%s'\'' >> ~/dextrose/xs-config/plugins.d/%s/Makefile",makef,pluginloc)
            system(cmd)
            print(cmd)}'
        fi
        cd $curdir
    done
    ;;

tree2plugins.d)
# input is list of files (find BUILDROOT with plugin name added),
# param1=treeroot output is files copied to ./files, manifest written
# usage: cat <find / of root> | xsc_tools tree2plugins.d ../linuxtree
    gawk  'BEGIN { RS = "\r" }
    {
    treeloc = "../linuxtree"
    src = $1
    tree = $1
    sub(/\./,"",tree)
    sub(/\./,"",src)
    if ($2 != ""){
        line = sprintf("cp %s%s plugins.d/%s/files/",treeloc,tree,$2)
        print( line )
        system(line)
        addline = sprintf("echo '%s' >> plugins.d/%s/%s.manifest",tree,$2,$2)
        print(addline)
        system(addline)
    }
    }' $2
    ;;
"treediff")
    diff -r . ~/dextrose/linuxtree
    ;;
*)
	ls  plugins.d
	;;
esac
