#!/bin/bash

if [ -f /etc/xsce/xsce.env ]
then
  . /etc/xsce/xsce.env
  cd $XSCE_DIR
fi

if [ ! -f xsce-network.yml ]
then
 echo "XSCE Playbook not found."
 echo "Please run this command from the top level of the git repo."
 echo "Exiting."
 exit
fi

export ANSIBLE_LOG_PATH="xsce-network.log"
ansible-playbook -i ansible_hosts xsce-network.yml --connection=local
