#!/bin/bash
#  This replaces the /etc/resolv.conf provided by DHCP with
#  one more to our liking.   It uses the school domain as the
#  default search domain, and the school DNS server is used first...

logger "changing /etc/resolv.conf for principal school server"
grep nameserver /etc/resolv.conf | tail -2 > /tmp/$$
cp /etc/sysconfig/olpc-scripts/resolv.conf /etc/resolv.conf
cat /tmp/$$ >> /etc/resolv.conf
rm /tmp/$$
