#!/bin/bash
#
# olpc-network-config  Starts the network config script
#
# chkconfig: - 05 95
#
# description:       olpc-network-config runs the first time a school server
#                    is booted after an image is installed, or after a
#                    change in hardware.  It checks for the
#                    existence of an /etc/sysconfig/olpc_net_config
#                    file.  If it doesn't find the file, it configures
#                    the network I/F files and runs depmod -a
#
CONFIG_FILE=/etc/sysconfig/olpc_net_config
NETWORK_CONFIG=/etc/sysconfig/olpc-scripts/network_config
DOMAIN_CONFIG=/etc/sysconfig/olpc-scripts/domain_config
start () {
       #  Check if we should even do anything.
       #  Search the configuration file for the run variable
       #  The following is a hack, but works well enough to get moving
	if [ ! -f $CONFIG_FILE ] ; then
	    $NETWORK_CONFIG 1 && $DOMAIN_CONFIG
	    RETVAL=$?
            [ $RETVAL -eq 0 ] && touch $CONFIG_FILE
	    #  This rebuilds the module dependency table to include
	    # the libertas drivers added manually.
	    depmod -a
	fi
	exit 0
}

case "$1" in
 start)
	start
	;;

 restart)
	start
	;;

 stop)
	exit 0
	;;

 *)
   echo $"Usage: $0 {start|restart|stop}"
   RETVAL=1
esac

exit $RETVAL
