install:

	install -D files/portal/incl/xs-portal.js  $(DESTDIR)/usr/share/xs-config/cfg/html/portal/incl/
	install -D files/portal/incl/banner.html  $(DESTDIR)/usr/share/xs-config/cfg/html/portal/incl/
	install -D files/portal/incl/service_list.php  $(DESTDIR)/usr/share/xs-config/cfg/html/portal/incl/
	install -D files/portal/images/xs_icon.png  $(DESTDIR)/usr/share/xs-config/cfg/html/portal/images/
	install -D files/portal/xs-portal.css  $(DESTDIR)/usr/share/xs-config/cfg/html/portal/
	install -D files/portal/index.hi.php  $(DESTDIR)/usr/share/xs-config/cfg/html/portal/
	install -D files/portal/index.en.php  $(DESTDIR)/usr/share/xs-config/cfg/html/portal/
	install -D files/etc/xs-portal.conf  $(DESTDIR)/usr/share/xs-config/cfg/etc
