#!/bin/sh -e
SERVICE_NAME=dhclient
CONFIG_LIST="/etc/dhclient.conf.in"
BACKUP_SUFFIX=old
. /etc/sysconfig/network

hostname $HOSTNAME
cp -f /usr/share/xs-config/cfg/etc/dhclient-hostname.conf /etc/dhclient.conf.in

short_host=`hostname -s`

for config in $CONFIG_LIST;
do
    if [ -e $config.in ]; then
	sed -e s/@@BASEDNSNAME3@@/$short_host/ $config.in ;
    else
	echo WARNING: Skipped $config - template file is missing!
    fi
done

exit 0


