#!/bin/sh -e
#  This file is called when the domain name is changed, to change any
#  dhcpd configuration files affected.
#
#  The first argument is the new domain name,

#  Copyright 2008, One Laptop per Child
#  Authors: John Watlington, Martin Langhoff
#  License: GPLv2

#  This is the name of the service (for stopping and restarting)
SERVICE_NAME=dhcpd

#  This config file has several replacements
#  so it is managed from its init script
service $SERVICE_NAME condrestart
