#!/bin/sh -e

#
# ejabberd now handles domain changes in the initrd script
#
SERVICE_NAME=ejabberd-xs

# Since for the community edition, we don't really expect all modules to be present
#   Just exit, and expect the user to do a restart

exit 0


service $SERVICE_NAME condrestart
