#!/bin/sh -e
#  This file is called when the domain name is changed, to change any
#  named configuration files affected.
#
#  The first argument is the new domain name,

#  Copyright 2008, One Laptop per Child
#  Authors: John Watlington, Martin Langhoff
#  License: GPLv2

#  This is the name of the service (for stopping and restarting)
SERVICE_NAME=named

#  This is a list of files related to this service which will have
#  the domain name globally replaced inside them
CONFIG_LIST="/etc/named-xs.conf /etc/named-xs.conf.tpl /var/named-xs/school.internal.zone.db /var/named-xs/school.internal.zone.in-addr.db"
#  This is the suffix which original versions of modified files will have
BACKUP_SUFFIX=old

new_name=$1

lanip=`ip addr ls eth0 | grep "inet " | awk '{print $2}' | awk -F '/' '$1=$1' | awk '{print $1}'`

for config in $CONFIG_LIST;
do
    if [ -e $config.in ]; then
	if [ -e $config ]; then
	    mv $config $config.$BACKUP_SUFFIX
	fi
        sed -i -e "s/@@BASEDNSNAME@@/$new_name/" $config.in > $config ;
    else
	echo WARNING: Skipped $config - template file is missing!
    fi
done

sed -i -e "s/@@LANIP@@/$lanip/" /var/named-xs/school.internal.zone.db ;
 
service $SERVICE_NAME restart

