install:

	install -D files/010-make-moodle-default.conf.in  $(DESTDIR)/etc/httpd/conf.d/010-make-moodle-default.conf.in
	install -D files/moodle-xs.service.in  $(DESTDIR)/etc/systemd/system/moodle-xs.service.in
	install -D files/moodle-xs-init  $(DESTDIR)/usr/libexec/moodle-xs-init
