install:
	install -D files/moodle-xs.service.in $(DESTDIR)/etc/systemd/system/
	install -D files/010-make-moodle-default.conf.in $(DESTDIR)/etc/httpd/conf.d/
	install -D files/moodle-xs-init $(DESTDIR)/usr/libexec/
