#!/bin/bash
# cat-parts - concatenate various files in a directory
# skipping

# keep going when something fails
set +e

if [ $# -lt 1 ]; then
	echo "Usage: cat-parts <dir>"
	exit 1
fi

if [ ! -d $1 ]; then
	echo "Not a directory: $1"
	exit 1
fi

# Ignore *~ and *, scripts
for i in $1/*[^~,] ; do
	[ -d $i ] && continue
	# Don't include *.{rpmsave,rpmorig,rpmnew,swp,cfsaved} scripts
	[ "${i%.cfsaved}" != "${i}" ] && continue
	[ "${i%.rpmsave}" != "${i}" ] && continue
        [ "${i%.rpmorig}" != "${i}" ] && continue
        [ "${i%.rpmnew}" != "${i}" ]  && continue
        [ "${i%.swp}" != "${i}" ]     && continue
	[ "${i%,v}" != "${i}" ]       && continue

	if [ -s $i ]; then
	    cat $i
	fi
done

exit 0
