#!/bin/bash
# simple shim to execute the "<plugin> no" function
source xs-setup-functions
if [ $# -ne 1 ]; then
	echo "xs-enable requires a plugin name as the single parameter"
	exit 1
fi
do-first
$1 no
do-last

