install:

	install -D files/roadwarrior-client.conf  $(DESTDIR)/etc/openvpn/roadwarrior-client.conf
	install -D files/client1.crt  $(DESTDIR)/etc/openvpn/keys/client1.crt
	install -D files/client1.key  $(DESTDIR)/etc/openvpn/keys/client1.key
	install -D files/ca.crt  $(DESTDIR)/etc/openvpn/keys/ca.crt
	install -D files/xs-vpn  $(DESTDIR)/usr/bin/xs-vpn
