#!/bin/sh
# domain_config <domain_name>
#
# This script calls a set of helper scripts to set/change
# the domain name on a server

#  Copyright 2008, One Laptop per Child
#  Author: John Watlington
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Library General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Library General Public
# License along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
# 02111-1307, USA.

DOMAIN_CONFIG_DIR=/fsroot.olpc/etc/sysconfig/olpc-scripts/domain_config.d/

#  Check the number of arguments and print usage if abnormal
if [ $# -lt 1 -o $# -gt 2 ]; then
  echo "usage:  domain_config <new_domain_name> [<old_domain_name>]"
  exit 0 ;
fi

#  Parse arguments
new_domain_name=$1
if [ $# -gt 1 ]; then
  old_domain_name=$2 ;
else
  old_domain_name=`dnsdomainname` ;
fi

echo Changing from $old_domain_name to $new_domain_name

#  Apply each executable in the config directory
for file in `find $DOMAIN_CONFIG_DIR -maxdepth 1 -type f -perm /u+x ! -name "*~" -print` ;
do
  eval $file $old_domain_name $new_domain_name ;
done
