install:
	install -D files/squid $(DESTDIR)/etc/sysconfig/olpc-scripts/domain_config.d/squid
	install -D files/squid.in $(DESTDIR)/etc/sysconfig/squid.in
	install -D files/squid-xs.conf.in $(DESTDIR)/etc/squid/squid-xs.conf.in
