install:

    install -D files/named-xs.conf.in  $(DESTDIR)/etc/named-xs.conf.in
    install -D files/named.in  $(DESTDIR)/etc/sysconfig/named.in
    install -D files/named  $(DESTDIR)/etc/sysconfig/olpc-scripts/domain_config.d/named
    install -D files/localdomain.zone  $(DESTDIR)/var/named-xs/localdomain.zone
    install -D files/localhost.zone  $(DESTDIR)/var/named-xs/localhost.zone
    install -D files/named.broadcast  $(DESTDIR)/var/named-xs/named.broadcast
    install -D files/named.ip6.local  $(DESTDIR)/var/named-xs/named.ip6.local
    install -D files/named.local  $(DESTDIR)/var/named-xs/named.local
    install -D files/named.rfc1912.zones  $(DESTDIR)/var/named-xs/named.rfc1912.zones
    install -D files/named.root  $(DESTDIR)/var/named-xs/named.root
    install -D files/named.root.hints  $(DESTDIR)/var/named-xs/named.root.hints
    install -D files/named.zero  $(DESTDIR)/var/named-xs/named.zero
    install -D files/school.external.zone.db  $(DESTDIR)/var/named-xs/school.external.zone.db
    install -D files/school.internal.zone.16.in-addr.db.in  $(DESTDIR)/var/named-xs/school.internal.zone.16.in-addr.db.in
    install -D files/school.internal.zone.32.in-addr.db.in  $(DESTDIR)/var/named-xs/school.internal.zone.32.in-addr.db.in
    install -D files/school.internal.zone.48.in-addr.db.in  $(DESTDIR)/var/named-xs/school.internal.zone.48.in-addr.db.in
    install -D files/school.internal.zone.db  $(DESTDIR)/var/named-xs/school.internal.zone.db
    install -D files/school.internal.zone.in-addr.db.in  $(DESTDIR)/var/named-xs/school.internal.zone.in-addr.db.in
    install -D files/dummy  $(DESTDIR)/var/named-xs/data/dummy
    install -D named.sh $(DESTDIR)/usr/share/xs-config/sh.d/
