install:
	install -D files/named-xs.conf.in  $(DESTDIR)/etc/named-xs.conf.in
	install -D files/named.in  $(DESTDIR)/etc/sysconfig/named.in
	install -D files/named  $(DESTDIR)/etc/sysconfig/olpc-scripts/domain_config.d/named
