install:
	install -D files/php.ini.in $(DESTDIR)/etc/
	install -D files/proxy_ajp.conf.in $(DESTDIR)/etc/httpd/conf.d/
	install -D files/httpd-xs.conf.in $(DESTDIR)/etc/httpd/conf/
	install -D files/httpd.in $(DESTDIR)/etc/sysconfig/
	install -D files/xs.conf $(DESTDIR)/usr/share/xs-config/cfg/etc/httpd/conf.d/
	install -D files/xs-http $(DESTDIR)/usr/share/xs-config/cfg/etc/sudoers.d/
	install -D files/xs-httpcache $(DESTDIR)/usr/bin/
