install:

	install -D files/proxy_ajp.conf.in  $(DESTDIR)/etc/httpd/conf.d/proxy_ajp.conf.in
	install -D files/httpd-xs-2.2.conf.in  $(DESTDIR)/etc/httpd/conf/httpd-xs-2.2.conf.in
	install -D files/httpd-xs-2.4.conf.in  $(DESTDIR)/etc/httpd/conf/httpd-xs-2.4.conf.in
	install -D files/php.ini.in  $(DESTDIR)/etc/php.ini.in
	install -D files/httpd.in  $(DESTDIR)/etc/sysconfig/httpd.in
	install -D files/xs-httpcache  $(DESTDIR)/usr/bin/xs-httpcache
	install -D files/xs-2.4.conf  $(DESTDIR)/usr/share/xs-config/cfg/etc/httpd/conf.d/xs-2.4.conf
	install -D files/xs-2.2.conf  $(DESTDIR)/usr/share/xs-config/cfg/etc/httpd/conf.d/xs-2.2.conf
	install -D files/xs-http  $(DESTDIR)/usr/share/xs-config/cfg/etc/sudoers.d/xs-http
