install:

	install -D files/proxy_ajp.conf.in  $(DESTDIR)/etc/httpd/conf.d/proxy_ajp.conf.in
	install -D files/httpd-xs.conf.in  $(DESTDIR)/etc/httpd/conf/httpd-xs.conf.in
	install -D files/php.ini.in  $(DESTDIR)/etc/php.ini.in
	install -D files/httpd.in  $(DESTDIR)/etc/sysconfig/httpd.in
	install -D files/xs-httpcache  $(DESTDIR)/usr/bin/xs-httpcache
	install -D files/xs.conf  $(DESTDIR)/usr/share/xs-config/cfg/etc/httpd/conf.d/xs.conf
	install -D files/xs-http  $(DESTDIR)/usr/share/xs-config/cfg/etc/sudoers.d/xs-http
	install -D httpd.sh $(DESTDIR)usr/share/xs-config/sh.d/
