install:
	install -D files/novnc.conf $(DESTDIR)/usr/share/xs-config/cfg/etc/httpd/conf.d/
	install -D files/self.pem $(DESTDIR)/usr/share/xs-config/cfg/etc/sysconfig/vnc/
	install -D files/xfce4-panel.xml $(DESTDIR)/usr/share/xs-config/cfg/etc/sysconfig/vnc/
	install -D files/xstartup $(DESTDIR)/usr/share/xs-config/cfg/etc/sysconfig/vnc/
	install -D files/vncserver@.service $(DESTDIR)/usr/share/xs-config/cfg/etc/systemd/system/
	install -D files/vncserverweb.service $(DESTDIR)/usr/share/xs-config/cfg/etc/systemd/system/
	install -D files/vnc_auto.html $(DESTDIR)/usr/share/xs-config/cfg/html/top/es/
	install -D files/vnc $(DESTDIR)/usr/share/xs-config/cfg/html/top/
	install -D files/vnc.js $(DESTDIR)/usr/share/xs-config/cfg/html/top/
