install:
	install -D files/etc/systemd/system/vncserverweb.service  $(DESTDIR)/usr/share/xs-config/cfg/etc/systemd/system/
	install -D files/etc/systemd/system/vncserver@.service  $(DESTDIR)/usr/share/xs-config/cfg/etc/systemd/system/
	install -D files/etc/httpd/conf.d/novnc.conf  $(DESTDIR)/usr/share/xs-config/cfg/etc/httpd/conf.d/
	install -D files/etc/sysconfig/vnc/xstartup  $(DESTDIR)/usr/share/xs-config/cfg/etc/sysconfig/vnc/
	install -D files/etc/sysconfig/vnc/xfce4-panel.xml  $(DESTDIR)/usr/share/xs-config/cfg/etc/sysconfig/vnc/
	install -D files/etc/sysconfig/vnc/self.pem  $(DESTDIR)/usr/share/xs-config/cfg/etc/sysconfig/vnc/
	install -D files/html/top/es/vnc_auto.html  $(DESTDIR)/usr/share/xs-config/cfg/html/top/es/
	install -D files/html/top/vnc.js  $(DESTDIR)/usr/share/xs-config/cfg/html/top/
