install:
	install -D files/vnc $(DESTDIR)/etc/sysconfig/vnc
	install -D files/vncserverweb.service $(DESTDIR)/usr/share/xs-config/cfg/etc/systemd/system/vncserverweb.service
	install -D files/vncserver@.service $(DESTDIR)/usr/share/xs-config/cfg/etc/systemd/system/vncserver@.service
	install -D files/novnc.conf $(DESTDIR)/usr/share/xs-config/cfg/etc/httpd/conf.d/novnc.conf
	install -D files/xstartup $(DESTDIR)/usr/share/xs-config/cfg/etc/sysconfig/vnc/xstartup
	install -D files/xfce4-panel.xml $(DESTDIR)/usr/share/xs-config/cfg/etc/sysconfig/vnc/xfce4-panel.xml
	install -D files/self.pem $(DESTDIR)/usr/share/xs-config/cfg/etc/sysconfig/vnc/self.pem
	install -D files/vnc $(DESTDIR)/usr/share/xs-config/cfg/html/top/vnc
	install -D files/vnc_auto.html $(DESTDIR)/usr/share/xs-config/cfg/html/top/es/vnc_auto.html
	install -D files/vnc.js $(DESTDIR)/usr/share/xs-config/cfg/html/top/vnc.js
