#!/bin/sh

# we'd like the user of this script to have root privilege
if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root" 1>&2
    exit 1
fi

# openvpn config file directory
dir=/etc/openvpn

if [ $# -eq 0 ]; then
    cmd="start"
else
    cmd=$1
fi
case $cmd in
"start" || "yes" || "on")
# load TUN/TAP kernel module
    modprobe tun

    openvpn --cd $dir --daemon --config roadwarrior-client.conf
    ;;
"stop" || "no" || "off")
    killall openvpn
    ;;
"status")
    pid=`ps -e|grep openvpn`
    if [ -z "$pid" ]; then
        echo "The openvpn process is not running"
    else
        echo "Openvpn is running with id $pid"
        ip=`ifconfig tun | gawk '(/netmask /) {print( $2);}'`
        echo "Local vpn tunnel address is $ip"
    fi
        
esac
