#!/bin/bash -x
sudo -u apache /usr/bin/php {{moodle_base}}/admin/cli/install.php \
"--wwwroot=http://schoolserver.lan/moodle --dataroot={{moodle_data}} \
--dbtype=pgsql --dbname=moodle --dbuser=Admin --dbpass=changeme \
--fullname=\"Your School\" --shortname=School \
--adminuser=admin --adminpass=changeme \
--non-interactive --agree-license"
