install:

	install -D files/dansguardian.conf.in  $(DESTDIR)/etc/dansguardian/dansguardian.conf.in
	install -D files/squid-xs-dg.conf.in  $(DESTDIR)/etc/squid/squid-xs-dg.conf.in
	install -D files/squid-dg.in  $(DESTDIR)/etc/sysconfig/squid-dg.in
