install:
	install -D files/idmgr.conf.in $(DESTDIR)/etc/
	install -D files/postgresql-512m.conf $(DESTDIR)/etc/pgsql-xs/
	install -D files/postgresql-256m.conf $(DESTDIR)/etc/pgsql-xs/
	install -D files/postgresql-2048m.conf $(DESTDIR)/etc/pgsql-xs/
	install -D files/postgresql-1024m.conf $(DESTDIR)/etc/pgsql-xs/
	install -D files/pgsql-xs $(DESTDIR)/etc/sysconfig/pgsql/
	install -D files/pg_hba.conf $(DESTDIR)/usr/share/xs-config/cfg/library/pgsql-xs/
	install -D files/postgresql-xs.service $(DESTDIR)/usr/share/xs-config/cfg/etc/systemd/system/
