install:
	install -D files/pathagar $(DESTDIR)/etc/pathagar
	install -D files/settings.py.in $(DESTDIR)/etc/pathagar/settings.py.in
	install -D files/pathagar.conf $(DESTDIR)/usr/share/xs-config/cfg/etc/httpd/conf.d/pathagar.conf
