install:
	install -D files/settings.py.in  $(DESTDIR)/etc/pathagar/settings.py.in
	install -D files/pathagar.conf  $(DESTDIR)/usr/share/xs-config/cfg/etc/httpd/conf.d/pathagar.conf
    install -D pathagar.sh $(DESTDIR)/usr/share/xs-config/sh.d/
