install:

	install -D files/settings.py.in  $(DESTDIR)/etc/pathagar/settings.py.in
	install -D files/pathagar.conf  $(DESTDIR)/etc/pathagar/pathagar.conf
	install -D files/pathagar.wsgi  $(DESTDIR)/etc/pathagar/pathagar.wsgi
