#!/bin/bash
# script to generate the taggit rpm required by Seth Woodward's github pathagar repo

git clone git://github.com/FinalsClub/django-taggit.git

cat <<EOF > django-taggit/setup.cfg
[bdist_rpm]
release = 4
packager = George Hunt <georgejhunt@gmail.com>
requires = django
EOF
cd django-taggit
python setup.py bdist_rpm -v
cd ~/django-taggit/dist
mkdir temp
cp django*noarch.rpm temp
cd temp
rpm2cpio django* | cpio -id
tree
