#!/bin/bash -x
# initialization specific to Trimslice hardware

# for debugging we need to identify use of uninitialized variables
set -u

FEDORA=`rpm -q fedora-release|gawk 'BEGIN {FS="-";}{print $3}'`
XSARCH=`uname -i`
 
# bring in packages unique to trimslice install
yum_cmd="yum -y install "
$yum_cmd  audit avahi dhcpd hostapd xs-config

# assign an ip address to the wifi hardware
ifconfig wlan0 172.18.96.1

# stop the firewall so that wifi can be internal lan
systemctl stop firewalld.service
systemctl disable firewalld.service

# load dhcpd and attach it to the wifi adapter, 
#+ so that it can be administered headless
sed -i  "s/@@BASEDNSNAME@@/local/" /etc/dhcp/dhcpd-ts.conf.in > \
        /etc/dhcp/dhcpd.conf
sed -i  "s/@@LAN_IF@@/wlan0/" /etc/sysconfig/dhcpd.in > \
        /etc/sysconfig/dhcpd
systemctl enable dhcpd.service
systemctl start dhcpd.service

# load avahi so that the wan ip address can be discovered
cp /etc/avahi/avahi-daemon.conf.in /etc/avahi/avahi-daemon.conf

# Access Point host software
systemctl enable hostapd.service
cp -f /etc/hostapd/hostapd.conf.in /etc/hostapd/hostapd.conf
systemctl start hostapd.service

# chain to the reqular non trimslice XSCE setup process
source xs-setup
