#!/bin/bash
# initialization specific to Trimslice hardware

FEDORA=`rpm -q fedora-release|gawk 'BEGIN {FS="-";}{print $3}'`
XSARCH=`uname -i`

# load avahi so that the wan ip address can be discovered
# load dhcpd and attach it to the wifi adapter, so that it can be administered headless
`
        yum_cmd="yum -y install "
        $yum_cmd  avahi dhcpd hostapd
        systemctl enable dhcpd.service
        systemctl enable hostapd.service
        ifconfig wlan0 172.18.96.1
        sed -i  "s/@@BASEDNSNAME@@/local/" "/etc/dhcp/dhcpd-ts.conf.in > \
                /etc/dhcp/dhcpd.conf
        systemctl start dhcpd.service
        cp -f /etc/hostapd/hostapd.conf.in /etc/hostapd/hostapd.conf
        systemctl start hostapd.service
        systemctl stop firewalld.service
        systemctl disable firewalld.service
