install:
	install -D files/ejabberd-xs.cfg.in $(DESTDIR)/etc/ejabberd/
	install -D files/ejabberd-xs $(DESTDIR)/etc/init.d/
	install -D files/ejabberd-xs $(DESTDIR)/etc/sysconfig/
	install -D files/ejabberd $(DESTDIR)/etc/sysconfig/olpc-scripts/domain_config.d/
	install -D files/ejabberd-xs.service.in $(DESTDIR)/etc/systemd/system/
	install -D files/xs-ejabberd-srg $(DESTDIR)/usr/bin/
	install -D files/10-ejabberdmoodle $(DESTDIR)/usr/share/xs-config/cfg/etc/sudoers.d/
