install:

	install -D files/ejabberd-xs.cfg.in  $(DESTDIR)/etc/ejabberd/ejabberd-xs.cfg.in
	install -D files/ejabberd-xs  $(DESTDIR)/etc/init.d/ejabberd-xs
	install -D files/ejabberd-xs  $(DESTDIR)/etc/sysconfig/ejabberd-xs
	install -D files/ejabberd  $(DESTDIR)/etc/sysconfig/olpc-scripts/domain_config.d/ejabberd
	install -D files/ejabberd-xs.service.in  $(DESTDIR)/etc/systemd/system/ejabberd-xs.service.in
	install -D files/xs-ejabberd-srg  $(DESTDIR)/usr/bin/xs-ejabberd-srg
	install -D files/10-ejabberdmoodle  $(DESTDIR)/usr/share/xs-config/cfg/etc/sudoers.d/10-ejabberdmoodle
	install -D ejabberd.sh $(DESTDIR)usr/share/xs-config/sh.d/
