#!/bin/bash -x
# Remove symlink in /library/content to autmounted usb drive
#
# based on a similar script in the xs-rsync package
# by Martin Langhoff <martin@laptop.org>
#
# and the adaptation for xs-activity-server by Douglas Bagnall
# <douglas@paradise.net.nz>
#
# by Tim Moody tim@timmoody.com

for f in `ls -d /library/content/USB*`;do
   TARGET=`ls -ld $f | gawk '{print $11}'`
   # if this target is not mounted, delete link to it
   mount | grep $TARGET
   if [ $? -ne 0 ]; then
     logger -p user.notice -t "70-usb-library" -- "Attempting to remove link to $TARGET."
     unlink  $f
   fi
done
