install:
	install -D files/xs-runansible  $(DESTDIR)/usr/bin/xs-runansible
	install -d -D $(DESTDIR)usr/share/xs-config/cfg/ansible/
	/bin/cp -rf files/playbooks/* $(DESTDIR)usr/share/xs-config/cfg/ansible
