#!/bin/sh
#
# Part of the OLPC XS Scripts
#
# Authors: Jerry Vonau <jvonau@shaw.ca>
#          Martin Langhoff <martin@laptop.org>
#  
if [ x${1} = x ]; then
    exit
else
    case $1 in
	wmesh0)
	    /sbin/ip addr flush dev msh0 2>/dev/null
	    /sbin/ifup msh0
	    ;;
	wmesh1)
	    /sbin/ip addr flush dev msh1 2>/dev/null
	    /sbin/ifup msh1
	    ;;
	wmesh2)
	    /sbin/ip addr flush dev msh2 2>/dev/null
	    /sbin/ifup msh1
	    ;;
    esac
fi
