#!/bin/sh
#
# Part of the OLPC XS Scripts
#
# Author: Martin Langhoff <martin@laptop.org>
#
if [ x${1} = x ]; then
  exit
else
case $1 in
    # if we are bringing up eth1
    # bring down the dummy if
    # and vice versa.
    "ifcfg-eth1")
	    /sbin/ifdown dummy0
   ;;
    "ifcfg-dummy0")
	    /sbin/ifdown eth1
esac
fi
