#!/bin/sh
#
# Part of the OLPC XS Scripts
#
# Authors: Jerry Vonau <jvonau@shaw.ca>
#          Martin Langhoff <martin@laptop.org>
#  
if [ x"${1}" = x ]; then
    exit
else
    case $1 in
	eth*|ppp*)
            lanaddr=`ip addr ls eth0 | grep "inet " | awk '{print $2}'`
            lanip=$lanaddr `awk -F '/' '$1=$1' | awk '{print $1}'`
            namedtpl=/etc/named-xs.conf.tpl
            namedconf=/etc/named-xs.conf
            locallan=/var/named-xs/school.internal.zone.db
            locallanin=/var/named-xs/school.internal.zone.db.in  
            FWD=""
            for i in `cat /etc/resolv.conf | grep nameserver | awk  '{print $2}'`; 
            do 
                if [ x\$i != x127.0.0.1 ]; then
                    FWD="$FWD $i;"
		else
                    exit    
		fi
            done 
	    cp $namedtpl $namedconf 
            logger "changing /etc/named-xs.conf using forwarders $FWD"
            sed -i -e "s/@@BASEDNSFWD@@/$FWD/" $namedconf
            cp $locallanin $locallan
            sed -e s/@@LANIP@@/$lanip/ $locallan ;

            logger "changing /etc/resolv.conf for principal school server"
	    cp /etc/sysconfig/olpc-scripts/resolv.conf /etc/resolv.conf  
	    ;;
    esac
fi

