#!/bin/bash
# routine to run on XS to  config for XO webdav access to school server
# 
# Remove "mod_ssl" package, so that the "/etc/httpd/conf.d/ssl.conf" 
# file is written afresh.
#
rpm -e --nodeps mod_ssl

# Install the packages (if not already).
#
#sudo yum -y install mod_ssl
rpm ivh --nodeps mod_ssl

# Make the directories (if not already), and set the permissions.
#
mkdir -p /var/www/web1/web/.Sugar-Metadata
chmod -R 0777 /var/www/web1/

# Some necessary tweaks in "httpd" service.
#
filename=/etc/httpd/logs
if [ -f $filename ];
then
	rm /etc/httpd/logs
fi
mkdir -p /etc/httpd/logs

# Create the password file for WebDAV.
#
htpasswd -bc /var/www/web1/passwd.dav test olpc

# Generate the ssl-key and certificate.
#
openssl req -new -newkey rsa:1024 -days 365 -nodes -x509 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" -keyout /etc/httpd/conf.d/ssl.key -out /etc/httpd/conf.d/ssl.crt

# Replace the key- and crt-path in conf-file, so that secure-transfer may be enabled.
#
SearchAndReplaceRegex()
{
	cat $1 | sed "s/$2/$3/g" > temp
	cat temp > $1
}

filename="/etc/httpd/conf.d/ssl.conf"
SearchAndReplaceRegex $filename "SSLCertificateKeyFile \/etc\/pki\/tls\/private\/localhost.key" "SSLCertificateKeyFile \/etc\/httpd\/conf.d\/ssl.key"          
SearchAndReplaceRegex $filename "SSLCertificateFile \/etc\/pki\/tls\/certs\/localhost.crt" "SSLCertificateFile \/etc\/httpd\/conf.d\/ssl.crt"

# Add the "VirtualHost" definition.
#
SearchAndDeleteLineContainingRegex()
{
	cat $1 | sed "/$2/d" > temp
	cat temp > $1
}

filename="/etc/httpd/conf.d/ssl.conf"
SearchAndDeleteLineContainingRegex $filename "<\/VirtualHost>"

cat << EOF >> /etc/httpd/conf.d/ssl.conf

        DocumentRoot /var/www/web1/web
        <Directory /var/www/web1/web/>
                Options Indexes MultiViews
                AllowOverride None
                Order allow,deny
                allow from all
        </Directory>

        Alias /webdav /var/www/web1/web

        <Location /webdav>
            DAV On
            AuthType Basic
            AuthName "webdav"
            AuthUserFile /var/www/web1/passwd.dav
            Require valid-user
        </Location>
</VirtualHost>
EOF

# Disable SElinux.
# 
# (F-17)
echo 0 > /sys/fs/selinux/enforce
#
# (F-14)
echo 0 > /selinux/enforce

# Change the startup preferences of services.
#
#/sbin/chkconfig httpd --levels 5 on
#/sbin/chkconfig iptables --levels 5 off
#/sbin/chkconfig ip6tables --levels 5 off


# Stop the required services (if not already).
#service iptables stop
#service ip6tables stop

# Restart the "httpd" service.
#
service httpd restart
systemctl restart httpd.service
