#!/usr/bin/python

""" Commit a file if
    - needs to be added
    - has changed

    This is just a bit of convenience scripts -- replaces
    a bit of ugly shell that was hard to make sane.

    Author: Martin Langhoff <martin@laptop.org>
    Copyright: One Laptop per Child
    License: GPLv2
"""
from subprocess import call, check_call, Popen, PIPE
import os.path, sys, os, re, tempfile, shutil, stat
from optparse import OptionParser

def main():

    parser = OptionParser(usage='%prog -m "msg" filea [fileb filec]')
    parser.add_option('-m', dest='msg', default='')
    (options, filepaths) = parser.parse_args()

    for fpath in filepaths:
        if os.path.exists(fpath):
            os.chdir(os.path.dirname(fpath))
            fname = os.path.basename(fpath)
            isnewcmd = ['git','ls-files', '--others',   fname]
            ismodcmd = ['git','ls-files', '--modified', fname]
            if Popen(isnewcmd, stdout=PIPE).communicate()[0]:
                check_call(['git', 'add', fname])
                msg = options.msg + ' - new file ' + fpath
                check_output = call(['git', 'commit', '-m', msg, fname])
            elif Popen(ismodcmd, stdout=PIPE).communicate()[0]:
                check_call(['git', 'add', fname])
                msg = options.msg + ' - ' + fpath
                check_call(['git', 'commit', '-m', msg, fname])

if __name__ == '__main__': main ()
