#!/bin/bash
#file: xs-set-env

#systemd does not permit bash substitutions in its environment setup
#so we execute xs related scripts to export settings for other services

# run setup scripts belonging to other packages
shopt -s nullglob
for i in /etc/sysconfig/olpc-scripts/set-env.d/*; do
	[ -x $i ] && $i
done
shopt -u nullglob
