#!/bin/bash
# Initial script to convert existing OS installation into an OLPC XS.
# Configures fundamental XS items.
# Usage: xs-setup [hostname]


DESTDIR=/

## Prepare a .git directory so xs-commitchanged
## can store its database...
if [ ! -d /etc/.git ];then
   pushd /etc
   git init
   chmod 700 .git
   popd
fi

###
### CLEANUP XS 0.4 to XS 0.5
###
# Remove old configs that are unambiguously old
OLDCONFIGS="/etc/sysconfig/network-scripts/ifcfg-dummy0
            /etc/sysconfig/network-scripts/ifcfg-br0
            /etc/sysconfig/network-scripts/ifcfg-br1
            /etc/sysconfig/network-scripts/ifcfg-br2  "
for FPATH in $OLDCONFIGS; do
    if [ -e "$DESTDIR/$FPATH" ];then
       /usr/bin/xs-commitchanged --remove -m 'Remove old conffile' "$DESTDIR/$FPATH"
    fi
done
# Remove ifcfg-ethX files that refer to libertas devices
# these have been replaced with wmeshX devices
for FPATH in $DESTDIR/etc/sysconfig/network-scripts/ifcfg-eth*; do
    # Here the implicit ls has incorporated $DESTDIR
    if grep -q '^ESSID=\"school-mesh-' "$FPATH" ;then
        /usr/bin/xs-commitchanged --remove -m 'Remove old libertas conffile' "$FPATH"
    fi
done
# remove eth1:1 if it's the 'school server master address'
FPATH="$DESTDIR/etc/sysconfig/network-scripts/ifcfg-eth1:1"
if [ -e "$FPATH" ];then
    if grep -q '^IPADDR=172.18.1.1' "$FPATH" ;then
        /usr/bin/xs-commitchanged --remove -m 'Remove old conffile' "$FPATH"
    fi
fi


## Update flag for httpd cache
if [ ! -e /etc/sysconfig/xs_httpcache_on ]; then
   if chkconfig --level 3 squid ; then
      touch /etc/sysconfig/xs_httpcache_on
   fi
fi

## Prepare config files
pushd /etc
# these don't need network settings
make -B -f xs-config.make earlyset
# seed low-level network conf and domain
/etc/sysconfig/olpc-scripts/network_config
/etc/sysconfig/olpc-scripts/domain_config
make -B -f xs-config.make networkset
popd

# Change the network infra we use
# note that 'network' now defaults to off
chkconfig --level 345 network on
if chkconfig --level 3 NetworkManager ; then
   chkconfig --del NetworkManager
fi

# Pg - prime the DB if needed.
if [ ! -e /library/pgsql-xs/data-8.3/PG_VERSION ];then
   /etc/init.d/pgsql-xs initdb
fi

# and set it to autostart
chkconfig --add pgsql-xs
chkconfig  postgresql off

# enable no-fsck-questions
chkconfig --add no-fsck-questions

service httpd condrestart
service rsyslog condrestart
