install:

    install -D files/ssl.conf.in  $(DESTDIR)/etc/httpd/conf.d/ssl.conf.in
    install -D files/upload.conf.in  $(DESTDIR)/etc/httpd/conf.d/upload.conf.in
    install -D files/upload.php  $(DESTDIR)/usr/share/xs-config/cfg/html/top/en/upload.php
    install -D one2many.sh $(DESTDIR)usr/share/xs-config/sh.d/
