install:
	install -D files/ssl.conf.in $(DESTDIR)/etc/httpd/conf.d/
	install -D files/upload.conf.in $(DESTDIR)/etc/httpd/conf.d/
	install -D files/upload.php $(DESTDIR)/usr/share/xs-config/cfg/html/top/en/
