install:

    install -D files/dhcpd-xs.conf.in  $(DESTDIR)/etc/dhcpd-xs.conf.in
    install -D files/dhcpd.in  $(DESTDIR)/etc/sysconfig/dhcpd.in
    install -D files/dhcpd  $(DESTDIR)/etc/sysconfig/olpc-scripts/domain_config.d/dhcpd
    install -D dhcpd.sh $(DESTDIR)/usr/share/xs-config/sh.d/
