#!/bin/bash
#  Directions for turning Squid caching on
SQUID_CACHEDIR="/library/cache"
SQUID_USER="squid:squid"

#  Make sure that the cache directory is present.
#  Squid crashes if it isn't (although it will create all subdirs...)
if [ ! -d $SQUID_CACHEDIR ]; then
    mkdir $SQUID_CACHEDIR
    chown $SQUID_USER $SQUID_CACHEDIR
fi

#  Turn squid on after the next reboot
/sbin/chkconfig --levels 345 squid on
#  Turn squid on now
/sbin/service squid start

#  Now, copy in a set of iptables that redirects forwarded traffic
#  to port 80 to port 3128 on this machine
cp /etc/sysconfig/olpc-scripts/iptables.principal.cache /etc/sysconfig/iptables
/sbin/service iptables restart

