#!/bin/bash
#  Directions for turning Squid caching off

#  First, restore a normal set of iptables
if [ -e /etc/sysconfig/xs_httpcache_on ];then
    rm /etc/sysconfig/xs_httpcache_on
fi
/sbin/service iptables restart

#  Turn it off now
/sbin/service squid stop
#  Turn it off after the next reboot
/sbin/chkconfig squid off
