install:

	install -D files/hosts.in  $(DESTDIR)/etc/hosts.in
	install -D files/motd.in  $(DESTDIR)/etc/motd.in
	install -D files/motd.olpc.in  $(DESTDIR)/etc/motd.olpc.in
	install -D files/rc.local  $(DESTDIR)/etc/rc.d/rc.local
	install -D files/rssh.conf.in  $(DESTDIR)/etc/rssh.conf.in
	install -D files/rsyslog.conf.in  $(DESTDIR)/etc/rsyslog.conf.in
	install -D files/sshd_config.in  $(DESTDIR)/etc/ssh/sshd_config.in
	install -D files/init.in  $(DESTDIR)/etc/sysconfig/init.in
	install -D files/pcspkr.modules  $(DESTDIR)/etc/sysconfig/modules/pcspkr.modules
	install -D files/sysctl.conf.in  $(DESTDIR)/etc/sysctl.conf.in
	install -D files/xs-apply-changes  $(DESTDIR)/root/xs-apply-changes
	install -D files/bootstrap-xo  $(DESTDIR)/usr/bin/bootstrap-xo
	install -D files/cat-parts  $(DESTDIR)/usr/bin/cat-parts
	install -D files/prep-storage.sh  $(DESTDIR)/usr/bin/prep-storage.sh
	install -D files/xs-mkaccount  $(DESTDIR)/usr/bin/xs-mkaccount
	install -D files/xs-services-check  $(DESTDIR)/usr/bin/xs-services-check
	install -D files/xs-setup  $(DESTDIR)/usr/bin/xs-setup
	install -D files/xs-setup-functions  $(DESTDIR)/usr/bin/xs-setup-functions
	install -D files/bashrc_xs.sh  $(DESTDIR)/usr/share/xs-config/cfg/etc/profile.d/bashrc_xs.sh
	install -D files/media.repo  $(DESTDIR)/usr/share/xs-config/cfg/etc/yum.repos.d/media.repo
