install:
	install -D files/resolv.conf.in $(DESTDIR)/etc/
	install -D files/ip6tables-config.in $(DESTDIR)/etc/sysconfig/
	install -D files/iptables-config.in $(DESTDIR)/etc/sysconfig/
	install -D files/network.in $(DESTDIR)/etc/sysconfig/
	install -D files/firewall-xs.in $(DESTDIR)/etc/sysconfig/olpc-scripts/
	install -D files/ip6tables-xs.in $(DESTDIR)/etc/sysconfig/olpc-scripts/
	install -D files/iptables-xs.in $(DESTDIR)/etc/sysconfig/olpc-scripts/
	install -D files/resolv.conf.in $(DESTDIR)/etc/sysconfig/olpc-scripts/
	install -D files/xs-domain-config $(DESTDIR)/usr/bin/
	install -D files/xs-gen-iptables $(DESTDIR)/usr/bin/
	install -D files/xs-resolvconf $(DESTDIR)/usr/bin/
	install -D files/xs-setup-network $(DESTDIR)/usr/bin/
	install -D files/xs-swapnics $(DESTDIR)/usr/bin/
	install -D files/10-olpc-net.rules $(DESTDIR)/usr/lib/udev/rules.d/
	install -D files/dhclient-exit-hooks $(DESTDIR)/usr/share/xs-config/cfg/etc/dhcp/
	install -D files/xs-net-device $(DESTDIR)/usr/share/xs-config/cfg/etc/NetworkManager/dispatcher.d/
	install -D files/dhcp $(DESTDIR)/usr/share/xs-config/cfg/etc/NetworkManager/system-connections/
	install -D files/eth0-wireless $(DESTDIR)/usr/share/xs-config/cfg/etc/NetworkManager/system-connections/
	install -D files/eth0-wireless-lan $(DESTDIR)/usr/share/xs-config/cfg/etc/NetworkManager/system-connections/
	install -D files/static $(DESTDIR)/usr/share/xs-config/cfg/etc/NetworkManager/system-connections/
	install -D files/Sugar\ Modem\ Connection $(DESTDIR)/usr/share/xs-config/cfg/etc/NetworkManager/system-connections/
	install -D files/iptables.service $(DESTDIR)/usr/share/xs-config/cfg/etc/systemd/system/
	install -D files/cnt_interface_info.php $(DESTDIR)/usr/share/xs-config/cfg/html/top/es/
	install -D files/cnt_net-config.php $(DESTDIR)/usr/share/xs-config/cfg/html/top/es/
	install -D files/lan_setup.php $(DESTDIR)/usr/share/xs-config/cfg/html/top/
