install:
	install -D files/monitrc.in  $(DESTDIR)/etc/monitrc.in
	install -D files/httpd  $(DESTDIR)/usr/share/xs-config/cfg/etc/monit.d/httpd
	install -D files/ejabberd  $(DESTDIR)/usr/share/xs-config/cfg/etc/monit.d/ejabberd
	install -D files/sshd  $(DESTDIR)/usr/share/xs-config/cfg/etc/monit.d/sshd
	install -D files/idmgr  $(DESTDIR)/usr/share/xs-config/cfg/etc/monit.d/idmgr
	install -D files/squid  $(DESTDIR)/usr/share/xs-config/cfg/etc/monit.d/squid
	install -D files/postgresql  $(DESTDIR)/usr/share/xs-config/cfg/etc/monit.d/postgresql
